import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Sidebar from '@/components/Sidebar'
import Filterbar from '@/components/Filterbar'
import AuthProvider from '@/context/AuthProvider'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + ' bg-[#1C1C24] text-white flex w-full min-h-screen flex-col gap-10'}>
        <AuthProvider>
          <Navbar/>
          <div className='flex w-full justify-center'>
            <Sidebar/>
            {children}
            <Filterbar/>
          </div>
        </AuthProvider>
      </body>
    </html>
  )
}
